<a href="https://colab.research.google.com/github/Logavarshini04/Rainfall-Prediction-Model/blob/main/RAINFALL_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Libraries

In [ ]:
import numpy as np
import pandas as pd

#Importing Dataset

In [ ]:
dataset=pd.read_csv("weatherAUS.csv")
x=dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y=dataset.iloc[:,-1].values

In [ ]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 3.6 25.3 ... 10.9 24.5 'No']
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']]


In [ ]:
print(y)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [ ]:
y=y.reshape(-1,1)

In [ ]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


#Dealing with Invalid Data

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)

In [ ]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 3.6 25.3 ... 10.9 24.5 'No']
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']]


In [ ]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


#Encoding Dataset

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
x[:,0]=le1.fit_transform(x[:,0])
le2=LabelEncoder()
x[:,4]=le2.fit_transform(x[:,4])
le3=LabelEncoder()
x[:,6]=le3.fit_transform(x[:,6])
le4=LabelEncoder()
x[:,7]=le4.fit_transform(x[:,7])
le5=LabelEncoder()
x[:,-1]=le5.fit_transform(x[:,-1])
le6=LabelEncoder()
y=le6.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(x)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 3.6 25.3 ... 10.9 24.5 0]
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]]


In [ ]:
print(y)

[0 0 0 ... 0 0 0]


#feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [ ]:
print(x)

[[-1.5270045   0.19169797 -0.044926   ... -0.01353307  0.02110819
  -0.53296232]
 [-1.5270045  -0.74708764  0.26444584 ...  0.03281942  0.38476354
  -0.53296232]
 [-1.5270045   0.11346584  0.34881998 ...  0.61995105  0.22475519
  -0.53296232]
 ...
 [ 1.21224943 -1.34165186  0.29257055 ... -0.94058301  0.41385597
  -0.53296232]
 [ 1.21224943 -1.06001618  0.51756825 ... -0.69336969  0.64659539
  -0.53296232]
 [ 1.21224943 -0.68450193  0.53163061 ... -0.29164805  0.63204918
  -0.53296232]]


#splitting dataset into Training dataset and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train)

[[ 1.56343583  0.26993011 -0.08711307 ...  0.28003274 -0.18253881
  -0.53296232]
 [-1.10558082  1.59987639  0.86912716 ...  1.45429598  0.85024239
   1.87630525]
 [-1.45676722 -0.38721982  1.82536739 ...  1.77876346  1.94120845
  -0.53296232]
 ...
 [-1.66747906 -0.04299843 -0.79023088 ... -0.38435305 -0.66256387
   1.87630525]
 [ 0.50987663 -0.70014836  0.39100704 ... -0.39980388  0.42840218
  -0.53296232]
 [ 1.63367311  1.22436215  1.16443664 ...  1.40794349  0.16657033
  -0.53296232]]


In [ ]:
print(y_train)

[0 0 0 ... 0 0 1]


#Training Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=150,random_state=0)
classifier.fit(x_train,y_train)


RandomForestClassifier(n_estimators=150, random_state=0)

In [ ]:
classifier.score(x_train,y_train)

0.9999296728027146

In [ ]:
print(y_test)

[0 0 0 ... 0 0 1]


In [ ]:
Y_pred=classifier.predict(x_test)

In [ ]:
print(Y_pred)

[0 0 0 ... 0 0 1]


In [ ]:
Y_pred=le6.inverse_transform(Y_pred)

In [ ]:
print(Y_pred)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


In [ ]:
print(y_test)

[0 0 0 ... 0 0 1]


In [ ]:
y_test=le6.inverse_transform(y_test)


In [ ]:
print(y_test)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


In [ ]:
y_test=y_test.reshape(-1,1)
Y_pred=Y_pred.reshape(-1,1)

In [ ]:
df = np.concatenate((y_test,Y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [ ]:
print(dataframe)

      Rain on Tommorrow Predition of Rain
0                    No                No
1                    No                No
2                    No                No
3                    No                No
4                    No                No
...                 ...               ...
28434                No                No
28435                No                No
28436                No                No
28437                No                No
28438               Yes               Yes

[28439 rows x 2 columns]


In [ ]:
dataframe.to_csv('prediction.csv')

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,Y_pred)

0.8564998769295685

In [ ]:
dataframe.to_csv('prediction.csv')